language: r
cache: packages
warnings_are_errors: false

# travis r package documentation:
# https://docs.travis-ci.com/user/languages/r/

r:
  - release


# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings


# for codecov
r_packages:
  - covr


# only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'master' && Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
