# RUN FROM THIS FOLDER
packwd <- getwd()

# add files to .Rbuildignore (files ignored during package building)
write("^specificity\\.Rproj$",     file=".Rbuildignore",append=FALSE)
write("^\\.Rproj\\.user$",         file=".Rbuildignore",append=TRUE)
write("^vignette$",                file=".Rbuildignore",append=TRUE)
write("^changelog.txt$",           file=".Rbuildignore",append=TRUE)
write("^github_stuff.sh$",         file=".Rbuildignore",append=TRUE)
write("^\\.travis.yml$",           file=".Rbuildignore",append=TRUE)
write("^test_results.txt$",        file=".Rbuildignore",append=TRUE)
write("^makedata$",                file=".Rbuildignore",append=TRUE)



library(devtools)
library(roxygen2)
library(Rcpp)
library(testthat)

usethis::use_package("ape")
usethis::use_package("parallel")
usethis::use_package("Rcpp")
usethis::use_package("fields")


# this looks for Rcpp::export in cpp files
Rcpp::compileAttributes("./")

document()

# ADD C++ namespace stuff to NAMESPACE file, because document() above OVERWRITES it:
# originally made via Rcpp::compileAttributes("./") above
lines2add <- readLines("additional_namespace/rcpp_namespace.txt")
write(lines2add, file="NAMESPACE", append=TRUE)

# add stuff to namespace that's not in BASE R but sure is in VANILLA R
# generated by (in shell):
#   cd ../
#   R CMD build specificity
#   R CMD check specificity_0.1.0.9000.tar.gz 
# look at specificity.Rcheck/00check.log
lines2add <- readLines("additional_namespace/vanillaR_namespace.txt")
write(lines2add, file="NAMESPACE", append=TRUE)



# install
setwd("../")
install("specificity")

# test
setwd("specificity/tests/")
### doing tests can take a minute! ###
capture.output(test_check("specificity"), file="../test_results.txt", split=TRUE)

# make pdf manual
# texinfo required: sudo apt-get install texinfo
setwd(packwd)
pack <- "specificity"
path <- find.package(pack)
system("rm specificity.pdf")
# commmand below requires: texlive-fonts-extra, texinfo (install both with apt)
system(paste(shQuote(file.path(R.home("bin"), "R")), "CMD", "Rd2pdf", shQuote(path)))


