// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pairwise_geo_mean
NumericVector pairwise_geo_mean(const NumericVector x);
RcppExport SEXP _specificity_pairwise_geo_mean(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_geo_mean(x));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_product
NumericVector pairwise_product(const NumericVector x);
RcppExport SEXP _specificity_pairwise_product(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_product(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_specificity_pairwise_geo_mean", (DL_FUNC) &_specificity_pairwise_geo_mean, 1},
    {"_specificity_pairwise_product", (DL_FUNC) &_specificity_pairwise_product, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_specificity(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
