# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairwise_product <- function(x) {
    .Call(`_specificity_pairwise_product`, x)
}

spec_core <- function(w, D) {
    .Call(`_specificity_spec_core`, w, D)
}

rao_sort_max <- function(w, D) {
    .Call(`_specificity_rao_sort_max`, w, D)
}

rao_genetic_max <- function(w, D, term_cycles = 10L, maxiters = 400L, popsize = 300L, keep = 5L, prc = 0.001) {
    .Call(`_specificity_rao_genetic_max`, w, D, term_cycles, maxiters, popsize, keep, prc)
}

