# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairwise_product <- function(x) {
    .Call(`_specificity_pairwise_product`, x)
}

rao1sp <- function(p, D, perm = FALSE, seed = 0L) {
    .Call(`_specificity_rao1sp`, p, D, perm, seed)
}

raoperms <- function(p, D, n_sim = 1000L, seed = 12345L) {
    .Call(`_specificity_raoperms`, p, D, n_sim, seed)
}

rao_genetic_max <- function(p, D, swap_freq, term_cycles = 10L, maxiters = 400L, popsize_perm = 150L, popsize_swap = 150L, keep = 5L, prc = 0.001) {
    .Call(`_specificity_rao_genetic_max`, p, D, swap_freq, term_cycles, maxiters, popsize_perm, popsize_swap, keep, prc)
}

